nodejs:
  # Don't modify below here
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  devmemoryLimits: 2Gi
  devmemoryRequests: 512Mi
  devcpuLimits: 1000m
  devcpuRequests: 500m
  autoscaling:
    enabled: false

idam-pr:
  redirect_uris:
    XUI:
      - https://xui-${SERVICE_NAME}.preview.platform.hmcts.net/oauth2/callback

aac-manage-case-assignment:
  java:
    ingressHost: manage-case-assignment-${SERVICE_NAME}.preview.platform.hmcts.net

xui-webapp:
  nodejs:
    ingressHost: xui-${SERVICE_NAME}.preview.platform.hmcts.net

ccd:
  ccd-api-gateway-web:
    nodejs:
      ingressHost: gateway-${SERVICE_NAME}.preview.platform.hmcts.net
  ccd-data-store-api:
    java:
      environment:
        OIDC_ISSUER: https://forgerock-am.service.core-compute-idam-{{ .Values.global.environment }}.internal:8443/openam/oauth2/hmcts
        CCD_S2S_AUTHORISED_SERVICES_CASE_USER_ROLES: civil_service,aac_manage_case_assignment
      ingressHost: ccd-data-store-api-${SERVICE_NAME}.preview.platform.hmcts.net
  ccd-definition-store-api:
    java:
      ingressHost: ccd-definition-store-${SERVICE_NAME}.preview.platform.hmcts.net